version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sotd_db
      POSTGRES_USER: krzysztof
      POSTGRES_PASSWORD: Kacpeek2402!

  sotd:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sotd

volumes:
  postgres_data:
  static_volume:
  media_volume: