# Generated by Django 4.0.4 on 2022-12-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchprediction',
            name='league',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
