# Generated by Django 4.0.4 on 2024-05-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='goalScorers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
