# Generated by Django 4.0.4 on 2022-08-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0002_alter_matchprediction_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfGamesToPredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EPL', models.IntegerField()),
                ('UCL', models.IntegerField()),
            ],
        ),
    ]
