# Generated by Django 4.0.4 on 2022-06-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0002_alter_matchprediction_goalscorer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevents',
            name='detail',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
