# Generated by Django 4.0.4 on 2022-12-11 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0002_matchprediction_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchprediction',
            name='match_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
