# Generated by Django 4.0.4 on 2024-05-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0002_alter_match_goalscorers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
