# Generated by Django 4.0.4 on 2022-06-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0003_matchevents_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevents',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='predicts.match'),
        ),
    ]
