# Generated by Django 4.0.4 on 2022-12-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0003_matchprediction_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchprediction',
            name='awayTeamName',
            field=models.CharField(default='N/A', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='homeTeamName',
            field=models.CharField(default='N/A', max_length=55),
            preserve_default=False,
        ),
    ]
