# Generated by Django 4.0.4 on 2024-06-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0003_alter_match_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='league_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
