# Generated by Django 4.0.4 on 2024-11-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0004_alter_match_date_alter_match_league_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(unique=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['match_id'],
            },
        ),
    ]
