# Generated by Django 4.0.4 on 2022-12-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0004_matchprediction_awayteamname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchevents',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchevents',
            name='player',
        ),
        migrations.RemoveField(
            model_name='matchevents',
            name='team',
        ),
        migrations.AddField(
            model_name='matchevents',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchevents',
            name='match_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchevents',
            name='player_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchevents',
            name='player_name',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchevents',
            name='team_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchevents',
            name='team_name',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
