# Generated by Django 4.0.4 on 2022-06-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_and_players', '0001_initial'),
        ('predicts', '0004_alter_matchevents_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='goalScorers',
            field=models.ManyToManyField(blank=True, related_name='goal_scorers', to='teams_and_players.player'),
        ),
    ]
