# Generated by Django 4.0.4 on 2024-11-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0005_matchdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotMobToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_fm_req', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
