# Generated by Django 4.0.4 on 2022-12-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0005_remove_matchevents_match_remove_matchevents_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('homeTeamResult', models.IntegerField()),
                ('awayTeamResult', models.IntegerField()),
                ('resultCode', models.CharField(choices=[('1', 'Home Team Won'), ('X', 'Draw'), ('2', 'Away Team Won')], max_length=1)),
                ('firstGoalScorerId', models.IntegerField(blank=True, null=True)),
                ('firstGoalScorerName', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
