# Generated by Django 4.0.4 on 2023-08-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0007_liveleague'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('monday', models.DateField()),
                ('sunday', models.DateField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
