# Generated by Django 4.0.4 on 2023-09-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0009_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.PositiveIntegerField(default=2023, verbose_name=range(2023, 2050)),
            preserve_default=False,
        ),
    ]
