# Generated by Django 4.0.4 on 2022-11-08 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('logo', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamsToTransferUpdate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='teams_and_players.team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('position', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=250)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams_and_players.team')),
            ],
            options={
                'ordering': ('team__name', 'position', 'name'),
            },
        ),
    ]
