# Generated by Django 4.0.4 on 2022-05-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_and_players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='founded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
