# Generated by Django 4.0.4 on 2022-08-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_and_players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsToTransferUpdate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('teams', models.ManyToManyField(blank=True, to='teams_and_players.team')),
            ],
        ),
    ]
