# Generated by Django 4.0.4 on 2024-05-25 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams_and_players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstotransferupdate',
            name='team',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamsToTransferUpdate',
        ),
    ]
