# Generated by Django 4.0.4 on 2022-08-31 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams_and_players', '0002_teamstotransferupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstotransferupdate',
            name='teams',
        ),
        migrations.AddField(
            model_name='teamstotransferupdate',
            name='team',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='teams_and_players.team'),
            preserve_default=False,
        ),
    ]
