# Generated by Django 4.0.4 on 2022-06-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
