# Generated by Django 4.0.4 on 2023-06-15 21:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_alter_weeklypoint_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypoint',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_points', to='leagues.league'),
            preserve_default=False,
        ),
    ]
