# Generated by Django 4.0.4 on 2023-06-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_monthlypoint_created_at_weeklypoint_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypoint',
            name='place',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
