# Generated by Django 4.0.4 on 2023-06-19 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_monthlypoint_place'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlypoint',
            unique_together=set(),
        ),
    ]
