# Generated by Django 4.0.4 on 2023-07-30 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_alter_monthlypoint_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypoint',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_points', to='leagues.league'),
            preserve_default=False,
        ),
    ]
